# Generated by Django 4.2.11 on 2024-03-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='product',
        ),
        migrations.RemoveField(
            model_name='material',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='material',
            name='warehouse_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='warehouse_app.product')),
            ],
        ),
    ]
